In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
# imported all the required libraries for linear regression on SMS data

#using pandas, splitted the data into label (who sent vs the message)
df = pd.read_csv("Data/SMSSpamCollection", sep='\t', header=None, names=['label', 'message'])
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
# we need to convert the labels into binary (0 for ham and 1 for spam)
df['target'] = (df['label'] == 'spam').astype(int)
df[['label', 'target']].value_counts()

label  target
ham    0         4825
spam   1          747
Name: count, dtype: int64

In [8]:
# on x-axis we have messages as our input and y is it spam or not spam
X = df['message']
y = df['target']

#spliting the data into 80% training and 20% for testing.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# converting each mesage into word counts
vec = CountVectorizer()
X_train_num = vec.fit_transform(X_train)
X_test_num = vec.transform(X_test)

In [10]:
# I create the LR model and allow enough iterations so it can finish learning.
model = LogisticRegression(max_iter=1000)
# train the model on the training messages (as numbers) and their labels.
model.fit(X_train_num, y_train)
# how well it does on the test set (fraction of messages it gets right).
print("Accuracy:", model.score(X_test_num, y_test))

Accuracy: 0.9883408071748879

In [13]:
import pandas as pd
cm = confusion_matrix(y_test, y_pred)
pd.DataFrame(cm, index=['actual ham', 'actual spam'], columns=['pred ham', 'pred spam'])

             pred ham  pred spam
actual ham        966          0
actual spam        13        136